<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-Commerce API Explorer</title>
    <style>
        :root { --ink:#17202a; --muted:#64707d; --line:#dbe1e7; --paper:#f5f7f8; --panel:#fff; --accent:#d65a3b; --teal:#167d78; --navy:#20364d; }
        * { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--paper); font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; }
        header { background:var(--navy); color:#fff; padding:34px clamp(20px,5vw,72px) 30px; } header .eyebrow { color:#f2a58f; text-transform:uppercase; letter-spacing:.13em; font-size:11px; font-weight:700; } h1 { margin:8px 0 4px; font:700 clamp(28px,4vw,46px)/1.05 Georgia,serif; } header p { margin:0; color:#cad5df; max-width:650px; }
        .toolbar { display:flex; gap:10px; align-items:center; flex-wrap:wrap; margin-top:24px; } input, textarea, select { width:100%; border:1px solid var(--line); border-radius:5px; background:#fff; color:var(--ink); padding:10px 11px; font:inherit; } .token { flex:1 1 420px; } .token input { background:#f8fbfd; }
        main { max-width:1180px; margin:28px auto 70px; padding:0 18px; display:grid; grid-template-columns:250px minmax(0,1fr); gap:24px; } aside { position:sticky; top:18px; align-self:start; } aside h2 { font-size:12px; text-transform:uppercase; letter-spacing:.1em; color:var(--muted); margin:0 0 10px; } nav button { display:block; width:100%; text-align:left; border:0; border-left:3px solid transparent; background:transparent; padding:8px 10px; color:var(--muted); cursor:pointer; } nav button:hover { color:var(--accent); border-color:var(--accent); }
        .intro { background:var(--panel); border:1px solid var(--line); padding:20px 22px; margin-bottom:18px; } .intro strong { color:var(--teal); } .group { margin:26px 0 10px; font:700 22px Georgia,serif; } .endpoint { border:1px solid var(--line); background:var(--panel); margin:10px 0; border-radius:6px; overflow:hidden; } summary { cursor:pointer; list-style:none; display:flex; align-items:center; gap:10px; padding:14px 16px; } summary::-webkit-details-marker { display:none; } summary:after { content:'+'; margin-left:auto; font-size:20px; color:var(--muted); } details[open] summary:after { content:'-'; } .method { min-width:64px; padding:4px 7px; border-radius:4px; font-size:11px; font-weight:800; text-align:center; color:#fff; } .GET { background:var(--teal); } .POST { background:#b97816; } .PUT { background:#386ca5; } .DELETE { background:#bc4d4d; } .path { font-family:ui-monospace,SFMono-Regular,Consolas,monospace; font-size:13px; } .auth { color:var(--muted); font-size:12px; margin-left:auto; } .panel { border-top:1px solid var(--line); padding:16px; display:grid; grid-template-columns:1fr 1fr; gap:14px; } .field label { display:block; color:var(--muted); font-size:12px; font-weight:700; margin-bottom:5px; } .field.full { grid-column:1/-1; } textarea { min-height:110px; resize:vertical; font-family:ui-monospace,SFMono-Regular,Consolas,monospace; font-size:12px; } .run { border:0; border-radius:5px; background:var(--accent); color:#fff; padding:10px 16px; cursor:pointer; font-weight:700; } .run:hover { filter:brightness(.92); } pre { grid-column:1/-1; background:#17202a; color:#d8e5ee; border-radius:5px; padding:14px; overflow:auto; min-height:54px; margin:0; font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace; white-space:pre-wrap; } .hint { color:var(--muted); font-size:12px; } @media(max-width:760px) { main { display:block; } aside { position:static; margin-bottom:24px; } nav { display:flex; overflow:auto; gap:4px; } nav button { white-space:nowrap; width:auto; } .panel { grid-template-columns:1fr; } .field.full { grid-column:auto; } .auth { display:none; } }
    </style>
</head>
<body>
<header>
    <div class="eyebrow">Local API documentation</div>
    <h1>E-Commerce API Explorer</h1>
    <p>Browse every registered endpoint and send real requests from your browser. No Postman setup required.</p>
    <div class="toolbar"><div class="token"><input id="token" type="text" placeholder="Paste Sanctum bearer token (optional for public endpoints)"></div><button class="run" type="button" onclick="document.getElementById('token').value=''">Clear token</button><a class="run" href="{{ route('api.docs.openapi') }}" target="_blank" style="text-decoration:none">OpenAPI JSON</a></div>
</header>
<main>
    <aside><h2>Sections</h2><nav id="nav"></nav></aside>
    <section id="content"><div class="intro"><strong>Base URL:</strong> <code>{{ url('/api/v1') }}</code><br><span class="hint">Register or log in first, then paste the returned token above. Path parameters use numeric seeded IDs.</span></div></section>
</main>
<script>
const groups = [
 {name:'Authentication', endpoints:[['POST','/auth/register','Public','{"name":"Dara","email":"dara@example.com","password":"password","password_confirmation":"password"}'],['POST','/auth/login','Public','{"email":"customer1@example.com","password":"password"}'],['GET','/auth/me','Sanctum',''],['POST','/auth/logout','Sanctum','']]},
 {name:'Catalog', endpoints:[['GET','/categories','Public',''],['GET','/categories/{category}','Public',''],['GET','/categories/{category}/products','Public',''],['POST','/admin/categories','Admin','{"name":"New Category","description":"Description"}'],['PUT','/admin/categories/{category}','Admin','{"name":"Updated Category"}'],['DELETE','/admin/categories/{category}','Admin',''],['GET','/products','Public',''],['GET','/products/search?search=phone','Public',''],['GET','/products/{product}','Public',''],['POST','/vendor/products','Vendor','{"category_id":1,"name":"Demo Product","sku":"DEMO-001","price":25,"stock":10}'],['PUT','/vendor/products/{product}','Vendor','{"price":30}'],['DELETE','/vendor/products/{product}','Vendor','']]},
 {name:'Customer tools', endpoints:[['GET','/cart','Sanctum',''],['POST','/cart/items','Sanctum','{"product_id":1,"quantity":2}'],['DELETE','/cart/items/{item}','Sanctum',''],['DELETE','/cart/clear','Sanctum',''],['GET','/wishlist','Sanctum',''],['POST','/wishlist/items','Sanctum','{"product_id":1}'],['DELETE','/wishlist/items/{product}','Sanctum',''],['DELETE','/wishlist/clear','Sanctum','']]}
];
const nav=document.getElementById('nav'), content=document.getElementById('content');
function esc(value){return value.replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function render(){ groups.forEach((group, gi)=>{ const id='group-'+gi; nav.insertAdjacentHTML('beforeend',`<button onclick="document.getElementById('${id}').scrollIntoView({behavior:'smooth'})">${group.name}</button>`); content.insertAdjacentHTML('beforeend',`<h2 class="group" id="${id}">${group.name}</h2>`); group.endpoints.forEach((e, ei)=>{ const key=`endpoint-${gi}-${ei}`; const [method,path,auth,body]=e; const hasBody=['POST','PUT'].includes(method); content.insertAdjacentHTML('beforeend',`<details class="endpoint"><summary><span class="method ${method}">${method}</span><span class="path">${path}</span><span class="auth">${auth}</span></summary><div class="panel"><div class="field"><label>Path values</label><input id="path-${key}" placeholder="Example: category=1, product=1"></div><div class="field"><label>Query string</label><input id="query-${key}" placeholder="Example: search=phone&per_page=10"></div>${hasBody?`<div class="field full"><label>JSON body</label><textarea id="body-${key}">${esc(body)}</textarea></div>`:''}<button class="run" type="button" onclick="send('${key}','${method}','${path}',${hasBody})">Send request</button><pre id="response-${key}">Response will appear here.</pre></div></details>`); }); }); }
async function send(key, method, template, hasBody){ const pathValues=document.getElementById('path-'+key).value.split(',').map(v=>v.trim().split('=')); let path=template; pathValues.forEach(([k,v])=>{if(k&&v) path=path.replace('{'+k+'}',encodeURIComponent(v));}); const query=document.getElementById('query-'+key).value.trim(); const url='{{ url('/api/v1') }}'+path+(query?(query.startsWith('?')?query:'?'+query):''); const output=document.getElementById('response-'+key); output.textContent='Loading...'; const headers={'Accept':'application/json'}; const token=document.getElementById('token').value.trim(); if(token) headers.Authorization=token.startsWith('Bearer ')?token:'Bearer '+token; let options={method,headers}; if(hasBody){headers['Content-Type']='application/json'; try{options.body=JSON.stringify(JSON.parse(document.getElementById('body-'+key).value||'{}'));}catch(e){output.textContent='Invalid JSON body: '+e.message;return;}} try{const response=await fetch(url,options); const text=await response.text(); let data; try{data=JSON.parse(text);}catch(e){data=text;} output.textContent=`HTTP ${response.status} ${response.statusText}\n\n`+JSON.stringify(data,null,2);}catch(e){output.textContent='Request failed: '+e.message;} }
render();
</script>
</body>
</html>